# Generated by Django 2.2 on 2020-08-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthlyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='User.User'),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earner', to='User.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='monthlyExpenses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlyExpenses', to='budget.Income'),
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='monthlyIncome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budget.Income'),
        ),
        migrations.AddField(
            model_name='monthlybudget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlyBudgets', to='User.User'),
        ),
    ]
