# Generated by Django 2.2 on 2020-08-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('deposit_date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earner', to='User.User')),
            ],
        ),
        migrations.CreateModel(
            name='monthlyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('monthlyExpenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlyExpenses', to='budgeting.Income')),
                ('monthlyIncome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='budgeting.Income')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlyBudgets', to='User.User')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_to', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('due_date', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='User.User')),
            ],
        ),
    ]
